apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-shop
  namespace: online-shop-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: online-shop
  template:
    metadata:
      labels:
        app: online-shop
    spec:
      containers:
        - name: online-shop
          image: subhik6/online-shop:v2
          ports:
            - containerPort: 80
          env:
            - name: APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: online-shop-config
                  key: APP_NAME
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: online-shop-config
                  key: ENV

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: online-shop-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: online-shop-secret
                  key: DB_PASS
